DROP DATABASE IF EXISTS CONTRACTORS;

CREATE DATABASE CONTRACTORS;

USE CONTRACTORS;
DROP TABLE IF EXISTS AGENCY;

CREATE TABLE `AGENCY` (
  	`ID` bigint(20) NOT NULL AUTO_INCREMENT,
   	`NAME` varchar(255) DEFAULT NULL,
	`EMAIL_ID` varchar(255) DEFAULT NULL,
  	`ADDRESS1` varchar(255) DEFAULT NULL,
  	`ADDRESS2` varchar(255) DEFAULT NULL,
   	`TOWN` varchar(255) DEFAULT NULL,
  	`CITY` varchar(255) DEFAULT NULL,
  	`COUNTRY` varchar(255) DEFAULT NULL,
	`POST_CODE` varchar(255) DEFAULT NULL,
  	`MOBILE` varchar(255) DEFAULT NULL,
  	`TELEPHONE` varchar(255) DEFAULT NULL,
 	 PRIMARY KEY (`id`),
 	 UNIQUE(NAME,EMAIL_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;